--[[

	This file is part of 'Masque: Entropy', an add-on for World of Warcraft. For bug reports,
	documentation and license information, please visit https://github.com/SFX-WoW/Masque_Entropy.

	* File...: Skins.lua
	* Author.: StormFX

	Entropy Skins

]]

local Masque = LibStub and LibStub("Masque", true)
if not Masque then return end

local _, Core = ...

----------------------------------------
-- Internal
---

local L = Core.Locale

----------------------------------------
-- Locals
---

local API_VERSION = 110207

-- Skin Info
local Version = "@project-version@"
local Websites = {
	"https://github.com/SFX-WoW/Masque_Entropy",
	"https://www.curseforge.com/wow/addons/masque-entropy",
	"https://addons.wago.io/addons/masque-entropy",
	"https://www.wowinterface.com/downloads/info8873",
}
local DESCRIPTION = L["A metallic version of Apathy in the color of %s ore."]

local PATH_BACKDROP = [[Interface\AddOns\Masque\Textures\Backdrop\]]

local PATH_BASE = [[Interface\AddOns\Masque_Entropy\Textures\Base\]]
local PATH_NORMAL = PATH_BASE.."Normal"
local PATH_BORDER = PATH_BASE.."Border"
local PATH_GLOW = PATH_BASE.."Glow"

----------------------------------------
-- Silver
---

Masque:AddSkin("Entropy - Silver", {
	API_VERSION = API_VERSION,
	Shape = "Square",

	-- [ Info ]
	Author = "StormFX",
	Description = DESCRIPTION:format("Silver"),
	Discord = "https://discord.gg/7MTWRgDzz8",
	Version = Version,
	Websites = Websites,

	-- [ UI ]
	Group = "Entropy",
	Order = 11,
	Title = "Silver",

	-- [ Skin ]
	-- Mask = nil,
	Backdrop = {
		Texture = PATH_BACKDROP.."Action",
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "BACKGROUND",
		-- DrawLevel = -1,
		Width = 26,
		Height = 26,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
		Item = {
			Texture = PATH_BACKDROP.."Item",
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "BACKGROUND",
			-- DrawLevel = -1,
			Width = 26,
			Height = 26,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
		Pet = {
			Texture = PATH_BACKDROP.."Pet",
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "BACKGROUND",
			-- DrawLevel = -1,
			Width = 26,
			Height = 26,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
	},
	Icon = {
		Texture = [[Interface\Icons\INV_Misc_Bag_08]], -- SlotIcon
		TexCoords = {0.03, 0.97, 0.03, 0.97},
		-- Color = {1, 1, 1, 1}, -- SlotIcon
		-- BlendMode = "BLEND", -- SlotIcon
		Width = 27,
		Height = 27,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotIcon = "Icon",
	Shadow = {
		Texture = PATH_BASE.."Shadow",
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = -1,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {1, 1, 1, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseStates = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseStates = nil,
		},
	},
	-- Disabled = Default.Disabled,
	Pushed = {
		-- Texture = [[Interface\Buttons\UI-Quickslot-Depress]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.5},
		BlendMode = "BLEND",
		DrawLayer = "BORDER",
		DrawLevel = 1,
		Width = 25,
		Height = 25,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseColor = true,
	},
	Flash = {
		-- Texture = [[Interface\Buttons\UI-QuickslotRed]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 0, 0, 0.4},
		BlendMode = "ADD",
		DrawLayer = "BORDER",
		DrawLevel = 0,
		Width = 25,
		Height = 25,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseColor = true,
	},
	Checked = {
		Texture = PATH_BORDER,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0.7, 0.9, 0.7},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotHighlight = "Checked",
	Border = {
		Texture = PATH_BORDER,
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	DebuffBorder = "Border",
	EnchantBorder = "Border",
	IconBorder = "Border",
	Gloss = {
		Texture = PATH_BASE.."Gloss",
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.5},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	NewAction = {
		-- Atlas = "bags-newitem",
		-- UseAtlasSize = false,
		Texture = PATH_GLOW,
		-- Color = {1, 1, 1, 1},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SpellHighlight = "NewAction",
	UpgradeIcon = {
		Atlas = "Bags-GreenArrow",
		-- UseAtlasSize = false, -- true
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 15,
		Height = 16,
		Point = "TOPLEFT",
		RelPoint = "TOPLEFT",
		OffsetX = 3,
		OffsetY = -4,
		-- SetAllPoints = nil,
	},
	IconOverlay = {
		Atlas = "AzeriteIconFrame",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 30,
		Height = 30,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	IconOverlay2 = {
		Atlas = "ConduitIconFrame-Corners",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 2,
		Width = 30,
		Height = 30,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	NewItem = {
		-- Atlas = "bags-glow-white",
		-- UseAtlasSize = false,
		Texture = PATH_GLOW,
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	QuestBorder = {
		Border = PATH_BASE.."Quest",
		Texture = PATH_BORDER,
		Color = {1, 0.8, 0, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 2,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ContextOverlay = {
		-- Texture = nil,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.7},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 4,
		Width = 30,
		Height = 30,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseColor = true,
	},
	SearchOverlay = "ContextOverlay",
	JunkIcon = {
		Atlas = "Bags-JunkCoin",
		-- UseAtlasSize = false, -- true
		-- Color = {1, 1, 1, 1},
		BlendMode = "BLEND",
		DrawLayer = "OVERLAY",
		DrawLevel = 3,
		Width = 16,
		Height = 16,
		Point = "TOPLEFT",
		RelPoint = "TOPLEFT",
		OffsetX = 5,
		OffsetY = -4,
		-- SetAllPoints = nil,
	},
	Name = {
		-- JustifyH = "CENTER",
		-- JustifyV = "BOTTOM",
		-- DrawLayer = "OVERLAY",
		Width = 27,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "BOTTOM",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = 1,
	},
	Duration = {
		-- JustifyH = "CENTER",
		-- JustifyV = "TOP",
		-- DrawLayer = "OVERLAY",
		Width = 27,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "TOP",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = -2,
	},
	Highlight = {
		Texture = PATH_BORDER,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.3},
		BlendMode = "ADD",
		-- DrawLayer = "HIGHLIGHT",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	HotKey = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "TOP",
		-- DrawLayer = "OVERLAY",
		Width = 27,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "TOPRIGHT",
		-- RelPoint = "TOPRIGHT",
		-- OffsetX = 0,
		OffsetY = -1,
	},
	Count = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "BOTTOM",
		-- DrawLayer = "OVERLAY",
		-- Width = 0,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "BOTTOMRIGHT",
		-- RelPoint = "BOTTOMRIGHT",
		-- OffsetX = 0,
		OffsetY = 1,
	},
	-- [ AutoCastShine (Classic) ]
	AutoCastable = {
		Texture = PATH_BASE.."Indicator",
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 0, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCastShine = {
		Width = 26,
		Height = 26,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 1,
		OffsetY = -1,
		-- SetAllPoints = nil,
	},
	-- [ AutoCastOverlay (Retail) ]
	-- AutoCast_Frame = Default.AutoCast_Frame,
	AutoCast_Shine = {
		Atlas = "UI-HUD-ActionBar-PetAutoCast-Ants",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 36, -- 41
		Height = 36, -- 41
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCast_Mask = {
		-- Atlas = "UI-HUD-ActionBar-PetAutoCast-Mask",
		-- UseAtlasSize = false,
		Texture = [[Interface\AddOns\Masque\Textures\Square\AutoCast-Mask]],
		-- TexCoords = {0, 1, 0, 1},
		Width = 24,
		Height = 24,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCast_Corners = {
		Atlas = "UI-HUD-ActionBar-PetAutoCast-Corners",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 30,
		Height = 30	,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = true,
	},
	-- [ Cooldowns ]
	Cooldown = {
		Texture = [[Interface\AddOns\Masque\Textures\Square\Mask]],
		EdgeTexture = [[Interface\AddOns\Masque\Textures\Square\Edge]],
		-- PulseTexture = [[Interface\Cooldown\star4]],
		Color = {0, 0, 0, 0.7},
		Width = 24,
		Height = 24,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ChargeCooldown = "Cooldown",
	-- [ SpellAlerts ]
	SpellAlert = {
		Height = 32,
		Width = 32,
		AltGlow = {
			Height = 36,
			Width = 36,
		},
		Classic = {
			Height = 26,
			Width = 26,
		},
		Modern = {
			Height = 26,
			Width = 26,
		},
		["Modern-Lite"] = {
			Height = 26,
			Width = 26,
		},
	},
	AssistedCombatHighlight = {
		Width = 36,
		Height = 36,
	},
})

----------------------------------------
-- Adamantite
---

Masque:AddSkin("Entropy - Adamantite", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Adamantite"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 1,
	Title = "Adamantite",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.7, 0.8, 0.9, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.7, 0.8, 0.9, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.7, 0.8, 0.9, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Bronze
---

Masque:AddSkin("Entropy - Bronze", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Bronze"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 2,
	Title = "Bronze",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 0.8, 0, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {1, 0.8, 0, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {1, 0.8, 0, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Cobalt
---

Masque:AddSkin("Entropy - Cobalt", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Cobalt"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 3,
	Title = "Cobalt",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.3, 0.7, 0.9, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.3, 0.7, 0.9, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.3, 0.7, 0.9, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Copper
---

Masque:AddSkin("Entropy - Copper", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Copper"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 4,
	Title = "Copper",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.8, 0.5, 0, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.8, 0.5, 0, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.8, 0.5, 0, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Fel Iron
---

Masque:AddSkin("Entropy - Fel Iron", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Fel Iron"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 5,
	Title = "Fel Iron",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.8, 1, 0.8, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.8, 1, 0.8, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.8, 1, 0.8, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Gold
---

Masque:AddSkin("Entropy - Gold", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Gold"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 6,
	Title = "Gold",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.8, 0.8, 0, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.8, 0.8, 0, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.8, 0.8, 0, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Iron
---

Masque:AddSkin("Entropy - Iron", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Iron"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 7,
	Title = "Iron",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.5, 0.5, 0.5, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.5, 0.5, 0.5, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.5, 0.5, 0.5, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Khorium
---

Masque:AddSkin("Entropy - Khorium", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Khorium"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 8,
	Title = "Khorium",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 0.8, 0.9, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {1, 0.8, 0.9, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {1, 0.8, 0.9, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Obsidium
---

Masque:AddSkin("Entropy - Obsidium", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Obsidium"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 9,
	Title = "Obsidium",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.3, 0.3, 0.3, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.3, 0.3, 0.3, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.3, 0.3, 0.3, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Saronite
---

Masque:AddSkin("Entropy - Saronite", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Saronite"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 10,
	Title = "Saronite",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.3, 0.9, 0.7, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.3, 0.9, 0.7, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {0.3, 0.9, 0.7, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})

----------------------------------------
-- Titanium
---

Masque:AddSkin("Entropy - Titanium", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Entropy - Silver",

	-- [ Info ]
	-- Author = Template.Author,
	Description = DESCRIPTION:format("Titanium"),
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 12,
	Title = "Titanium",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_NORMAL,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 0.7, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {1, 1, 0.7, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- UseStates = nil,
		-- SetAllPoints = nil,
		Item = {
			Texture = PATH_NORMAL,
			-- TexCoords = {0, 1, 0, 1},
			Color = {1, 1, 0.7, 1},
			-- EmptyTexture = [[Interface\AddOns\Masque_Entropy\Textures\Base\Normal]],
			-- EmptyCoords = {0, 1, 0, 1},
			EmptyColor = {0.3, 0.3, 0.3, 0.5},
			-- BlendMode = "BLEND",
			-- DrawLayer = "ARTWORK",
			-- DrawLevel = 0,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- UseStates = nil,
			-- SetAllPoints = nil,
		},
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	-- Highlight = Template.Highlight,
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})
